### ISSUE TITLE
False-negative on GitHub Actions

### ISSUE THREAD

**Issue by ai** [chalk/supports-color#106]
GitHub Actions CI supports color output. But `chalk` use black/white output there.

Seems like we have a false-negative detection at `support-color`.

I am fixing the problem with `FORCE_COLOR=2` right now.

**Comment by Qix-** [comment]
Hey @ai  :) Do you have an example I could take a look at? Chalk behaves differently based on how it's used (e.g. with pipes). Can't confirm if this is a bug or not without seeing if there's another issue.

**Comment by ai** [comment]
Sure, here is an [example](https://github.com/logux/logux.io/commit/222430bd9308932e353830f9d1983f943b0d3ac7/checks?check_suite_id=379357654) with `FORCE_COLOR=2`.

I have Node.js script with simple code like:

```
#!/usr/bin/env node

import chalk from 'chalk'

process.stdout.write(chalk.red('Test'))
```

When I run this script in CI with:

```yaml
      - name: Deploy files
        run: ./script.js
```

I have no colors and I start to have colors only with:

```yaml
      - name: Deploy files
        run: ./script.js
        env:
          FORCE_COLOR: 2
```

**Comment by Qix-** [comment]
Which version of chalk? `chalk@3` uses `supports-color@7.1.0` which includes #102, so this should be working.

Can you verify you're at chalk >= 3.0?

**Comment by ai** [comment]
```
"chalk": "^3.0.0",
```

I checked that [I have `GITHUB_ACTIONS`](https://github.com/logux/logux.io/commit/31b61a35500012a8281b5f62583664f8c9f72556/checks?check_suite_id=379396530) env.

Maybe some other check disable it?

**Comment by Qix-** [comment]
Very strange. Could you see if `process.stdout. isTTY` is truthey?

**Comment by ai** [comment]
`process.stdout.isTTY` is `undefined`: https://github.com/logux/logux.io/commit/6392d1a99a61710b8a5e5f08e36a2796ea689ff5/checks?check_suite_id=379405498

**Comment by Qix-** [comment]
That's why. For whatever reason, Node doesn't seem to think it's outputting to a TTY. This is probably on Github not setting up a proper pseudo terminal environment for actions to run in.

Unfortunately, there's no _great_ way to properly solve this without Github's help. The environment checks have to come after the TTY checks, otherwise we'd break people piping output to other programs (which would get polluted with escape sequences).

Unless we think Github can fix this with PTY support, unfortunately this is a nofix - `FORCE_COLOR=1`/`=2` will have to be used instead.

Sorry about that :/ Wish I had a better answer.

**Comment by Qix-** [comment]
Took the liberty of contacting Github about it. If they respond positively, I'll open this back up and track it ^^

**Comment by ai** [comment]
Seems like we should call @chrispat here

**Comment by ai** [comment]
I also created an issue (hope I used right place for it) https://github.com/actions/virtual-environments/issues/218

Thanks for finding the actual reason.

**Comment by Qix-** [comment]
Re-opening for visibility, then :)

**Comment by ai** [comment]
Can we just force colors on `GITHUB_ACTIONS` even without `isTTY` since we know that GH supports colors?

**Comment by Qix-** [comment]
You can, sure. But as a general rule, no. It would break anyone using pipes.

**Comment by ai** [comment]
Oh, I forgot about pipes

**Comment by SimenB** [comment]
Solved with https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/?

**Comment by mshima** [comment]
This should be fixed with https://github.com/chalk/supports-color/commit/651576a5fabfa489660b48f50a7f2e5ed7676997

A new release should be great.

**Comment by viceice** [comment]
I think this can be closed, as it's fixed with v7.2

**Comment by Qix-** [comment]
Yep, thanks for the reminder. Let me know if this isn't solved by upgrading.

**Comment by rethab** [comment]
@Qix- from what I can tell, this not solved yet:

In the code, this check:

```javascript
	if (haveStream && !streamIsTTY && forceColor === undefined) {
		return 0;
	}
```

comes before this part:

```javascript
	if ('CI' in env) {
      // etc...
```

When run on GitHub Actions, the first condition already returns 0. This is because of this open issue in the runner: https://github.com/actions/runner/issues/241

**Comment by mrmckeb** [comment]
Does anyone have this working? I'm also seeing level 0 returned due to `isTTY` being `undefined`.

**Comment by peternewman** [comment]
As mentioned at the top @mrmckeb FORCE_COLOR=2 works. See for example my PR here:
https://github.com/openstreetmap/iD/pull/9692/files

Or any of the others referencing this issue and linked to it.

**Comment by mrmckeb** [comment]
That's a fine solution, thanks. I was wondering if anyone had a solution that end-users wouldn't need to implement.

For now, I've implemented this:
```ts
if (env.GITHUB_ACTIONS) {
  const supportsColor = createSupportsColor({ isTTY: !env.TEST });
  if (supportsColor) {
    chalk.level = supportsColor.level;
  }
}
```
